# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nextjs:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        container_name: faespe-node
        stdin_open: true
        volumes:
            - './:/usr/src/app'
            - '/usr/src/app/node_modules'
